apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  containers:
  - name: c0
    image: nginx
    command: ["/bin/bash", "-c", "echo HELLO  !!!; echo"]
  - name: c1
    image: nginx
    command: ["/bin/bash", "-c", "echo WORLD  !!!; echo"]
